#!/usr/bin/bash
source 0SOURCE
cd ${WORK_DIR}

## Clean up the intermediate files
\rm -r *.Reps.psr
\rm -r *.Reps.psl.tailer*

## clean up *.sample, *.fasta and *.fa files
for indel in q t
do
cd ${WGvarINDEL_DIR}/${indel}
mkdir -p ${WGvarINDEL_DIR}/${indel}/file_sample
mv *.sample ${WGvarINDEL_DIR}/${indel}/file_sample

mkdir -p ${WGvarINDEL_DIR}/${indel}/file_contig
mv *.fa ${WGvarINDEL_DIR}/${indel}/file_contig

mkdir -p ${WGvarINDEL_DIR}/${indel}/file_gap
mv *_GAP_*.fasta ${WGvarINDEL_DIR}/${indel}/file_gap

done

