#!/usr/bin/bash
source ./0SOURCE

cd ${run_DIR}
mv *_env_*.vcf ${data_DIR}

mv *.fxmt.* ${scratch}
mv *.addrep.* ${scratch}
mv *.mkdup.* ${scratch}
mv *.sorted.* ${scratch}
mv *.intervals ${scratch}
mv *.metrics ${scratch}
